keyword: developer

sources:
  - remoteok
  - remotive
  - greenhouse
  - lever
  - workday
  - custom_careers
  - ashby
  - smartrecruiters
  - bamboohr
  - jobvite
  - icims
  - personio
  - recruitee

limits:
  llm_input_limit: 50
  max_bullets: 20

filters:
  remote_only: false
  strict_senior_only: false
